services:
  - type: web
    name: runasone
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REDIRECT_URI
        sync: false